project:
  type: book
  output-dir: docs

book:
  title: "Jamovi"
  site-url: "https://wdkeyzer.github.io/Jamovi/"
  chapters:
    - index.qmd
    - 01-Descriptive-Data/Jamovi-Descriptive-Data_nl.qmd
    - 05-Chi-squared/Jamovi-Chi-Squared_nl.qmd

format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true
    theme:
      light: flatly
      dark: darkly

callout-appearance: simple