project:
  type: website
  output-dir: docs

website:
  title: "Jamovi"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: 01-Descriptive-Data/Jamovi-Descriptive-Data_nl.qmd
        text: Beschrijvende statistiek en normaliteit
      - href: 05-Chi-squared/Jamovi-Chi-Squared_nl.qmd
        text: Kruistabellen en Chi-kwadraattest

format:
  html:
    toc: true
    number-sections: true
    theme:
      light: flatly
      dark: darkly

callout-appearance: simple

